### ISSUE TITLE
set a time boundary for tests perfomed on the same vehicles

### ISSUE THREAD

**Issue by Guli-Y** [hanbo-e/wimlds_emissions#18]

**Comment by IreneSophia** [comment]
Set a boundary of two months, the first test is kept. Put this in the data.py file

**Comment by Guli-Y** [comment]
I just checked, several things:
1. since you need to groupby('VIN'), cleaning the VIN string is necessary (data.py line 74)
2. Before going for month, it is also necessary to take the first record of the day. This is reason, you lost many fail records. Or alternatively, rank the data by START_SDATE before everything.
3. Last point is just my opinion about the gap, maybe 1 month instead of 2m. We can of course check out both and see which is better.
